# Generated by Django 5.0.6 on 2025-01-31 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedDoodles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doodle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doodle_saved', to='cram.doodle')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_saved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='saveddoodles',
            constraint=models.UniqueConstraint(fields=('user_id', 'doodle_id'), name='unique_saves'),
        ),
    ]
