# Generated by Django 5.0.6 on 2024-09-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doodle',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
