# Generated by Django 5.0.6 on 2024-07-07 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=30, upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('doodlr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doodler', to='cram.user')),
            ],
        ),
    ]
