# Generated by Django 5.0.6 on 2026-09-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0002_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.FileField(default='/cram/asset/GHOSTCOVERART.png', upload_to=''),
        ),
    ]
