# Generated by Django 5.0.6 on 2024-10-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0002_alter_doodle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doodle',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
