# Generated by Django 5.0.6 on 2025-01-31 00:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0002_saveddoodles_saveddoodles_unique_saves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20)),
                ('doodle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_post', to='cram.doodle')),
            ],
        ),
    ]
