# Generated by Django 5.0.6 on 2025-01-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
