# Generated by Django 5.0.6 on 2026-09-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0003_alter_user_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_image',
            new_name='profile_picture',
        ),
    ]
