# Generated by Django 5.0.6 on 2024-10-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
