# Generated by Django 5.0.6 on 2026-09-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0004_rename_user_image_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='default_picture.png', upload_to=''),
        ),
    ]
