# Generated by Django 5.0.6 on 2026-09-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='profile_pictures/default_picture.png', upload_to=''),
        ),
    ]
