# Generated by Django 5.0.6 on 2026-09-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doodle',
            name='image',
            field=models.FileField(upload_to='doodles/'),
        ),
    ]
