# Generated by Django 5.0.6 on 2025-01-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0006_remove_user_phone_number_alter_user_password_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='pinned_doodle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pinned_doodle', to='cram.doodle'),
            preserve_default=False,
        ),
    ]
