# Generated by Django 5.0.6 on 2024-10-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='https://doodler-bucket.s3.amazonaws.com/default_NjtZ1Pn.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA3EJA3YAZXJN53FHB%2F20241023%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20241023T220113Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=4d2e909cfd49ed2725f97a1022503f220511d7e119dfa87083c98c2d51bc54fd', upload_to=''),
        ),
    ]
