# Generated by Django 5.0.6 on 2026-09-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0007_alter_doodle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='profile_pictures/default_picture.png', upload_to='profile_pictures/'),
        ),
    ]
