# Generated by Django 5.0.6 on 2024-11-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='https://doodler-bucket.s3.us-east-2.amazonaws.com/default.jpg', upload_to=''),
        ),
    ]
