# Generated by Django 5.0.6 on 2025-01-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0009_alter_user_pinned_doodle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pinned_doodle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pinned_doodle', to='cram.doodle'),
        ),
    ]
