# Generated by Django 5.0.6 on 2024-11-18 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yeahs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HPY', 'yeah!!'), ('NRM', 'yeah'), ('SAD', 'yeah..'), ('CFD', 'yeah.?')], max_length=6)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='cram.doodle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
