# Generated by Django 5.0.6 on 2024-11-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0011_yeahs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yeahs',
            old_name='user',
            new_name='liker',
        ),
    ]
