# Generated by Django 5.0.6 on 2024-11-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0012_rename_user_yeahs_liker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
