# Generated by Django 5.0.6 on 2024-11-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0013_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
